// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIMS.Infrastructure.Persistence.DbContexts;

#nullable disable

namespace PIMS.Migrations.SQLite.Migrations
{
    [DbContext(typeof(PIMSDbContext))]
    partial class PIMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("PIMS.Domain.Document", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveTaskID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ActiveTaskID")
                        .IsUnique();

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("PIMS.Domain.ProjectTask", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousTaskID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("DocumentID");

                    b.HasIndex("PreviousTaskID")
                        .IsUnique();

                    b.ToTable("ProjectTasks", (string)null);
                });

            modelBuilder.Entity("PIMS.Domain.Document", b =>
                {
                    b.HasOne("PIMS.Domain.ProjectTask", "ActiveTask")
                        .WithOne()
                        .HasForeignKey("PIMS.Domain.Document", "ActiveTaskID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActiveTask");
                });

            modelBuilder.Entity("PIMS.Domain.ProjectTask", b =>
                {
                    b.HasOne("PIMS.Domain.Document", "Document")
                        .WithMany("Tasks")
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIMS.Domain.ProjectTask", "PreviousTask")
                        .WithOne()
                        .HasForeignKey("PIMS.Domain.ProjectTask", "PreviousTaskID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Document");

                    b.Navigation("PreviousTask");
                });

            modelBuilder.Entity("PIMS.Domain.Document", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
